name: Update README Terminal Preview

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:     

permissions:
  contents: write         
  pages: read
  id-token: write

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright@1.48.0

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Capture screenshot of live terminal
        run: |
          node - << 'EOF'
          const { chromium } = require('playwright');

          (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage({
              viewport: { width: 1280, height: 800 },
            });

            await page.goto('https://tamiloreo.github.io/TamiloreO/', {
              waitUntil: 'networkidle'
            });

            await page.waitForTimeout(1500);

            const terminal = await page.$('main.terminal');
            if (terminal) {
              await terminal.screenshot({
                path: 'assets/terminal-preview.png'
              });
            } else {
              await page.screenshot({
                path: 'assets/terminal-preview.png',
                fullPage: false
              });
            }

            await browser.close();
          })();
          EOF

      - name: Commit and push if changed
        run: |
          git config user.name "terminal-bot"
          git config user.email "actions@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add assets/terminal-preview.png
            git commit -m "chore: auto-update terminal preview"
            git push
          else
            echo "No visual changes, nothing to commit."
          fi
